### ISSUE TITLE
Verb precedence for Broot

### ISSUE THREAD

**Issue by 9999years** [9999years/broot.nvim#6]
This may require upstream changes. I want to identify a verb in my main `conf.toml`:

```toml
[[verbs]]
key = "enter"
invocation = "edit"
shortcut = "e"
apply_to = "file"
external = "nvim {file}"
leave_broot = false
```

And then override it with a verb in my `nvim.toml`:

```toml
[[verbs]]
key = "enter"
invocation = "edit"
shortcut = "e"
apply_to = "file"
external = "broot.nvim edit +{line} {file}"
from_shell = true
```

As it stands, the second definition in `nvim.toml` just gets ignored.
